### ISSUE TITLE
MP4 videos 

### ISSUE THREAD

**Issue by wolfhowling** [nicolafranchini/VenoBox#100]
Does this plugin support mp4 videos from an external url without the iframe, because when i set data-vbtype to video it does not load the video instead it loads a 404 error page from my site, if i load it in iframe it loads but i get black bars and cant edit the body of an external iframe and while i could set the with and height of the frame to match the video i have multiple videos of different sizes and i would like to avoid setting any fixed dimension for easier responsiveness.

Thanks

**Comment by nicolafranchini** [comment]
Nope, I'm sorry, Iframes and responsiveness aren't big friends :D 
the data-vbtype="video" only supports Vimeo and YouTube, and uses iFrames with proportional width/height based on viewport breakpoints (take a look at venobox.css).
you could try adjusting that with some additional js
