### ISSUE TITLE
Hide spinner when popup has been loaded

### ISSUE THREAD

**Issue by jslirola** [nicolafranchini/VenoBox#101]
Hello, I checked the available options but I didn't see this feature. If I have a button with venobox and data-vbtype="iframe" and low height, the spinner keep visible.

How can I hide the spinner when the iframe is loaded?

![bootbox_spinner](https://user-images.githubusercontent.com/6697559/28016491-d4f1ba0c-6574-11e7-9720-72458cf6ef8a.jpg)

**Comment by Ryan-Haines** [comment]
This isn't an available feature in the venobox plugin, but it's still possible.

You'll have to add a callback to cb_post_open that checks if the iframe is loaded, and hides the spinner on success:

https://stackoverflow.com/questions/9249680/how-to-check-if-iframe-is-loaded-or-it-has-a-content/17873704
