### ISSUE TITLE
Venobox lightbox size

### ISSUE THREAD

**Issue by antton** [nicolafranchini/VenoBox#102]
Hi, 

I'm trying with a custom venobox to open the windows as big as I can but it looks like it has kind of max size.

Am I wrong or doing something incorrectly?

Thanks!

**Comment by Ryan-Haines** [comment]
You can edit the venobox.css file

```
.vbox-content{
  width: 100%;
  height: 100%;
}

.vbox-content img{
    max-width: 100%;
    height: 100%;
}
```

**Comment by nicolafranchini** [comment]
Yep, depends on the content type, but for images the max width is the actual width of the image (so if the image is 600px and the screen 1200px, the image won't be stretched).

the easiest way would be linking bigger images.
