### ISSUE TITLE
Script fails after mobile browser scroll

### ISSUE THREAD

**Issue by myhre23** [nicolafranchini/VenoBox#103]
The script seems to fail when scrolling on a mobile browser for an image gallery. It runs once and works fine but if you scroll after it has run it then stops working and the image href just loads. Any ideas?

**Comment by shivarajnaidu** [comment]
could you please give me some more details about context.. like mobile you have tested...etc.. and reproduction steps for this issue.. It will be helpful to point out the issue.

**Comment by myhre23** [comment]
The script seemed to fail using an old version of JQuery. So updating the jquery file to the latest code fixed the issue. Thanks
