### ISSUE TITLE
Local video playing?

### ISSUE THREAD

**Issue by Rpstone0** [nicolafranchini/VenoBox#104]
Hey there,

Is there a way to host and play local videos through VenoBox? Right now it seems it's setup only for Youtube and Vimeo,  is there a work around for it?

Thanks!

**Comment by nicolafranchini** [comment]
Hi, you could include an hidden HTML5 `<video>` on page, and call it with `data-vbtype="inline"`, or `data-vbtype="iframe"` if hosted elsewhere

**Comment by thEpisode** [comment]
Please include it in "usage" section

**Comment by divinerites** [comment]
Is it possible to provide a n example ? Would be great.
I can't suceed to have the right behaviour for the local video (with or without id).
Latest Chrome on Mac

```html 
<video hidden id="toto" width="320" height="240" controls>
    <source src="/videos/video1.mp4" type="video/mp4">
    Your browser does not support the video tag.
</video>
                <!-- Video locale -->

                  <div class="pulse-container">
                    <div class="pulse-box">
                      <a class="venobox play-icon icon-center" data-autoplay="true" data-vbtype="inline"
                        href="#toto"><i class="fa fa-play text-secondary"></i></a>
                    </div>
                  </div>
```

**Comment by divinerites** [comment]
Solution is : 

```
                <div id="titi" style="display:none;">
                  <video controls preload="metadata">
                    <source src="/videos/video1.mp4" type="video/mp4">
                    Your browser does not support the video tag.
                  </video>
                </div>

               <div class="pulse-container">
                    <div class="pulse-box">
                      <a class="venobox play-icon icon-center" data-autoplay="true" data-vbtype="inline"
                        href="#titi"><i class="fa fa-play text-secondary"></i></a>
                    </div>
                </div>
```

**Comment by nicolafranchini** [comment]
The latest version also supports html5 videos, in .mp4, .ogg, .webm format

**Comment by ItsSalman99** [comment]
> Solution is :
> 
> ```
>                 <div id="titi" style="display:none;">
>                   <video controls preload="metadata">
>                     <source src="/videos/video1.mp4" type="video/mp4">
>                     Your browser does not support the video tag.
>                   </video>
>                 </div>
> 
>                <div class="pulse-container">
>                     <div class="pulse-box">
>                       <a class="venobox play-icon icon-center" data-autoplay="true" data-vbtype="inline"
>                         href="#titi"><i class="fa fa-play text-secondary"></i></a>
>                     </div>
>                 </div>
> ```

worked for me.. Thanks man
