### ISSUE TITLE
close venobox when click button

### ISSUE THREAD

**Issue by reezal** [nicolafranchini/VenoBox#105]
Hi

i'd like to be able to close venobox from the content body other than 'X', is it possible?

my case are, in the content body, it has a check box and button. after check the check box and click the button, it will close a venobox.

as i know, closeVbox() function is not accessible globally.

thanks.

**Comment by Ryan-Haines** [comment]
This is possible.

Add this code after a venobox is opened:

`jQuery(".vbox-container, .vbox-content").on('touchend click', function(event){
  if(!jQuery(event.target).hasClass('figlio')){
    jQuery(".vbox-close").click();
  }
});`

Hopefully a future version of venobox will support this in a more elegant manner.

**Comment by nicolafranchini** [comment]
Hi guys, sorry for my late response, actually there's already the method **.VBclose()**, as suggested inside the [demo](http://veno.es/venobox/) under "Methods": just declare .venobox() as variable when you initialize it:
```
    var test = $('.venobox').venobox();

    // close current item clicking on .closeme
    $(document).on('click', '.closeme', function(e){
        test.VBclose();
    });
```

**Comment by reezal** [comment]
Hi, there is an error when using VBclose

Here is the inspect from Firefox

> `TypeError: test.VBclose is not a function`

**Comment by reezal** [comment]
hi, i've tried using VBclose(). It work on inline but doesn't work on iframe

**Comment by jaessi** [comment]
@reezal 
I was having the same problem with iFrame content, so I fixed it via:
``
$('document').on('click', '.extra-close-button', function() {
   $('.vbox-close').trigger('click');
});

**Comment by faizlongbow** [comment]
Hi i have problem using venobox with is cannot pitch the images zoom out and zoom in using android OS, using IOS the image is working fine.
