### ISSUE TITLE
alternative ways to open venobox

### ISSUE THREAD

**Issue by simon1tan** [nicolafranchini/VenoBox#110]
Venobox seems to be constrained to only work with links. There needs to be other ways to opening venobox. For example, I would like to click on a button and javascript can call venobox to open ajax or iframe. Options can be used to define an href or other criterias.

Another lightbox that I've used, magnific popup, does this pretty well:
`$.magnificPopup.open({
	items: { 
		src: '/new'
	}
	, type: 'iframe'
});
`

**Comment by nicolafranchini** [comment]
There's the `data-href=""` option if you are not using links:

https://jsfiddle.net/veno/tup9L9ye/

**Comment by BigglesZX** [comment]
@simon1tan
I solved this same issue by creating a (virtual) anchor element in JS, calling `.venobox()` on it, then triggering a click.

Something like this:

```javascript
$("<a href='...'></a>").venobox().trigger('click');
```

You can use the `gallItems` option to support a gallery of multiple items (just create multiple anchors). And you don't have to insert the element(s) into the DOM either; you can just trigger them as above.

Not the most elegant solution but it does the job.

**Comment by kovacm** [comment]
> There's the `data-href=""` option if you are not using links:
> 
> https://jsfiddle.net/veno/qzmk36fa/

But how I can custom edit "data-href" with java script?

**Comment by nicolafranchini** [comment]
> But how I can custom edit "data-href" with java script?

https://jsfiddle.net/y6L9p2tr/1/

**Comment by kovacm** [comment]
I just use simple: 

document.getElementById("myButton").setAttribute("data-href", "submit.php?poison=coke");

**Comment by nicolafranchini** [comment]
Yep, it is the same thing, in plain javascript instead of using jquery

**Comment by kovacm** [comment]
Thanks for fast response! :)
