### ISSUE TITLE
Move close button to top of popup window not screen

### ISSUE THREAD

**Issue by cwarnick28** [nicolafranchini/VenoBox#111]
Is there a way to have the Close X button to display at the top of the popup window rather than at the top of the whole display window? I have a popup thats 70% width and 300px in height and want the X to show at the top right of that popup window and not all the way at the top right of the page and I can't  use CSS because everything is responsive based on screen size.

**Comment by jaessi** [comment]
I tried to look for a way to do this from the popup itself, but it didn't seem possible given the container structure. Luckily, I'm mostly using it with the iFrame option.

If you also happen to be using the iFrame option for the content, you could create the close button on the content pages (then align fixed to the top right), then have that button trigger a close click event on the parent close button (which I hide with CSS).
