### ISSUE TITLE
Margin / padding / overlay close problem.

### ISSUE THREAD

**Issue by tomanatura** [nicolafranchini/VenoBox#112]
Hello, 
I would like to set up Venobox to be able close vbox-container by clicking **anywhere** inside it. But it is impossible  in / because of "margin arrea". 
Ive tried to change ` /* -------- CENTER FRAME -------- */` to padding, it is working on desktop, but on mobile, first image in set is not vertically centered (has wrong padding value).
Is there other or better way how to be able close venobox anywhere in vbox-container?    
Thanks you

**Comment by sasoriza** [comment]
How has this been an issue for so long? This really should be fixed.

**Comment by nicolafranchini** [comment]
You can try this #115
