### ISSUE TITLE
Settings covered up after upgrade to WordPress 4.9

### ISSUE THREAD

**Issue by jaessi** [nicolafranchini/VenoBox#113]
Upon upgrading WP to 4.9, I had a black box over the settings tab content. I was able to get rid of it via applying CSS to the admin stylesheet:

```
body.settings_page_venobox .wp-color-result {
    display: none;
}

**Comment by nicolafranchini** [comment]
Hi, you should report this to the author of the wordpress plugin, I've only created and mantain the original VenoBox.js jQuery plugin.

**Comment by jaessi** [comment]
Sorry! I didn't realize that.
