### ISSUE TITLE
Overlay close does not work on iPad, and full overlay is not clickable

### ISSUE THREAD

**Issue by jawinn** [nicolafranchini/VenoBox#115]
The tap on the overlay does not close the modal on iPad. This can be partly fixed by changing line 426 from:

`$(document).on('click', closeclickclass, function(e){`
to
`$(document).on('click touchstart', closeclickclass, function(e){`

The overlay click does not appear to work on the whole overlay though (separate issue?). Only clicking/tapping the center part of it within .vbox-content will cause it to close. This can be seen on the demo site when clicking above or below the content on the "Inline" modal.

**Comment by yBussi** [comment]
same problem here, i would like to get answer to fix this issue

**Comment by benrugg** [comment]
Thanks for posting this, @jawinn. I was pulling my hair out just now, trying to get it to close on iOS. 

For the part of this issue you mentioned about only some of the overlay being clickable/tappable, it can  be solved by adding one more case in the `if` statement inside that function. It needs to allow clicks/taps on `'.vbox-container'` as well. So the full code would be:

```
$(document).on('click touchstart', closeclickclass, function(e) {
    if ($(e.target).is('.vbox-overlay') ||
      $(e.target).is('.vbox-content') ||
      $(e.target).is('.vbox-close') ||
      $(e.target).is('.vbox-preloader') ||
      $(e.target).is('.vbox-container')
    ) {
        closeVbox();
    }
});
```

(I haven't tested this in all the situations that this plugin can be used for... I'm only using it for displaying videos).
