### ISSUE TITLE
Problem w/ video modal (Chrome Mac and Windows)

### ISSUE THREAD

**Issue by rioulesmills** [nicolafranchini/VenoBox#122]
Good morning, 

Just for information, there is a bug with the video modal on Chrome (Mac and Windows).
![gifmodal](https://user-images.githubusercontent.com/35811081/40358495-ba4cadbc-5dbf-11e8-9a58-f2d91aa88a3c.gif)
The bug also occurs on your presentation site, so I think this one is generalized.

I will try to find the cause and will inform you, I wanted to report it to you in case you already knew of this concern.

Sincerely,

**Comment by ShaneRoode** [comment]
Looks like we are having this issue too. Looks like the problem is only happening with Chrome - Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by VickyShen** [comment]
Hey, not sure if this helps. But when I go into venobox.css and comment out the box-shadow style for .figlio, the issue is gone. I'm not sure why that happened though, it used to work fine with the same code.

**Comment by sonipb** [comment]
@VickyShen 
i had same problem. Your solution works. great! thanks.

**Comment by nicolafranchini** [comment]
Hi, and thanks for the reports, I've just tried the online demo with Chrome 68.0.3440.106 (Official Build) (64 bit), and the issue seems gone, also keeping the box-shadow
