### ISSUE TITLE
Is there anyway to add zoom or magnify function - thanks!

### ISSUE THREAD

**Issue by ethnik192** [nicolafranchini/VenoBox#127]
Just wanted to see if there's code I can insert to add zoom or magnify function - love this plugin!  Thanks.

**Comment by nicolafranchini** [comment]
I've no code for that, sorry, you can possibly use venobox in iframe or inline mode, and load another zoom function directly inside the content.

**Comment by endlessuniverse** [comment]
Hi. It would be great to have a ready state to hook panzoom function like:

`    $(document).on('lity:ready', function(e, lightbox) {
        lightbox.find('img').panzoom();
    });`

Thank you!

**Comment by nicolafranchini** [comment]
Hi, check the documentation, under Callbacks, you can use the function 
```
$('.venobox').venobox({
    cb_post_open : function(obj, gallIndex, thenext, theprev){
        // ....here your code
    }
});
```
https://veno.es/venobox/

**Comment by endlessuniverse** [comment]
Thank you very much!
