### ISSUE TITLE
How to customize the iframe layout for Embedded Videos

### ISSUE THREAD

**Issue by iamdeadman** [nicolafranchini/VenoBox#128]
Hi, 

Is there a way to customize the iframe that opens upon clicking the video item ? 
like provide the iframe a custom template or something along those lines so that we can customize the player layout to something like this - 

![image](https://user-images.githubusercontent.com/3391877/48418467-5fdb4780-e77b-11e8-8971-cb58adf23023.png)

**Comment by nicolafranchini** [comment]
You can't customize the iframe content, as it's a cross-origin content, you can possibly customize the window, which is the class `.venoframe` inside venobox.css
