### ISSUE TITLE
popup is not triggered some time on page load for AJAX loaded content

### ISSUE THREAD

**Issue by o-nkar** [nicolafranchini/VenoBox#129]
I have done an Instagram feed gallery using venobox popup plugin inline method, but sometimes it doesn't load the popup on click when the user visits the page. after a page refresh, it works well and good.

Gallery content is loaded via AJAX call and then popup code.

Thanks
Onkar

**Comment by nicolafranchini** [comment]
I don't know, it could be the gallery content is not fully loaded when venobox is initialized, even if the ajax call is done, and the link is not yet ready.
