### ISSUE TITLE
Pop up isn't triggering, spinner charging indefinely

### ISSUE THREAD

**Issue by juanrubio96** [nicolafranchini/VenoBox#132]
When I click on the trigger button the spinner begins to charge but Popup never initializes.

![Screenshot_1](https://user-images.githubusercontent.com/45278119/54762396-cf05f400-4bd2-11e9-9af0-786a93ffb0bd.png)

As you can see, here's the code:

![Screenshot_2](https://user-images.githubusercontent.com/45278119/54762679-52bfe080-4bd3-11e9-9adf-a5a2629c9f16.png)

![Screenshot_3](https://user-images.githubusercontent.com/45278119/54762686-55223a80-4bd3-11e9-9ce8-3f948ac634d3.png)

But later those screens I insert other attributes to the script and they are working, just the video isn't working.

![image](https://user-images.githubusercontent.com/45278119/54762867-b0542d00-4bd3-11e9-984b-1629d8088d4b.png)

![image](https://user-images.githubusercontent.com/45278119/54763019-fd380380-4bd3-11e9-98dd-b051c1124aec.png)

Thanks in advance!

**Comment by nicolafranchini** [comment]
it sould be `data-vbtype="video"` and not `datavbtype="video"`
