### ISSUE TITLE
Pause other audio?

### ISSUE THREAD

**Issue by StephenMeehan2016** [nicolafranchini/VenoBox#134]
Hi, thanks for such a great lightbox plugin.

I'm using VenoBox to display auto playing YouTube videos in a lightbox - it works really well.

However, I have an `<audio>` element elsewhere on my page, If that's being played and then I open a lightbox with an auto play YouTube video the `<audio>` can still be heard.

Is there a way to turn off any other audio that might be playing when a lightbox is opened?

Thanks again.

**Comment by nicolafranchini** [comment]
You should call the stop all sounds function (depending on what are you using to play the audio) inside the callback `cb_pre_open`
<pre>
var venoOptions = {
    cb_pre_open : function(obj){
         // call here the function to stop your audio
    },
}
$('.venobox').venobox(venoOptions);
</pre>
