### ISSUE TITLE
One link for a carousel style show?

### ISSUE THREAD

**Issue by pkiula** [nicolafranchini/VenoBox#135]
Hi. Thank you for this clean looking codebase. Love it. However, we have a need to show one link or button, which needs to open up a modal with prev-next navigation for multimedia: text, video, and a few images. How can I do this? The demos don't link this, and a few attempts I've made don't show this easily how to do this. Thanks!

**Comment by nicolafranchini** [comment]
Hi, you can use the `data-gall=".."` option to support a gallery of multiple items (just create multiple anchors and set only the first one visible). 
e.g:
<pre>
&lt;a class="venobox" data-gall="custom-gallery" href="first-item"&gt;Click me&lt;/a&gt;
&lt;a class="venobox" data-gall="custom-gallery" href="second-item"&gt;&lt;/a&gt;
&lt;a class="venobox" data-gall="custom-gallery" href="third-item"&gt;&lt;/a&gt;
...
</pre>
