### ISSUE TITLE
Hi =)

### ISSUE THREAD

**Issue by korshunovmax** [nicolafranchini/VenoBox#139]
Hi, sometimes really missing simple functionality, of course I added it for my use. Novice programmers ask me about a double click, maybe someone will come in handy. Thanks for your work

```
venobox: function(options) {
    var defaults = {
        click: 'click',
    }
}

obj.on(option.click, function(e){
    ...
}

//use
$('.element').venobox({click: 'dblclick'});

```

**Comment by nicolafranchini** [comment]
Thank you. Maybe I will add that option. It should be slightly different now, because the script doesn't use anymore jQuery
