### ISSUE TITLE
Local video playing?

### ISSUE THREAD

**Issue by ismailzia** [nicolafranchini/VenoBox#141]
could i use video in my local with venobox 
thank you

**Comment by divinerites** [comment]
See https://github.com/nicolafranchini/VenoBox/issues/104#issuecomment-716195983

**Comment by hridoy533y** [comment]
> 
> 
> could i use video in my local with venobox
> thank you

hey bro how you do this

**Comment by divinerites** [comment]
> hey bro how you do this

Just read the post above 
See https://github.com/nicolafranchini/VenoBox/issues/104#issuecomment-716195983
