### ISSUE TITLE
Dimension of the modal window

### ISSUE THREAD

**Issue by Philippe-M** [nicolafranchini/VenoBox#146]
Hello, I use venobox (1.9) to display two types of content: youtube and an ajax call. For the former everything works well. For the ajax case I have a problem with the size of the modal window. It does not adapt to the size of its content. For my case the content is a maximum height of 650px but as it does not adapt I have a large margin at the top and bottom (same for the sides).

Is there a possibility to modify the behavior so that the window adapts to the size of its content automatically?

Philippe.

**Comment by nicolafranchini** [comment]
You could try to use the new `maxWidth` option of venobox 2
