### ISSUE TITLE
Not working with old browser

### ISSUE THREAD

**Issue by tiendungdev** [nicolafranchini/VenoBox#150]
VenoBox not working with old browser

https://prnt.sc/uqemzg

My project has a problem: https://vutruso.com/du-an/giao-dien-shop-ban-giay-online-juno/

**Comment by DAnn2012** [comment]
Hello @tiendungdev 

it seems to be an issue with jQuery caused by a recent update of the **LiteSpeed Cache** plugin:

https://wordpress.org/support/plugin/litespeed-cache/

**Comment by tiendungdev** [comment]
Find a solution to resolve this issue?!
