### ISSUE TITLE
Why  .css  Uncaught SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by hgalytoby** [nicolafranchini/VenoBox#159]
Sorry i just learned the front end 

![image](https://user-images.githubusercontent.com/50397689/119214057-6722ff00-baf6-11eb-8815-0344888c2103.png)
![image](https://user-images.githubusercontent.com/50397689/119214065-6db17680-baf6-11eb-8fef-6a0c92256456.png)

head load
```
<link rel="stylesheet" href="/venobox/venobox.min.css" />
```

body load
```
<script src="jquery.js"></script>
<script src="venobox/venobox.min.js"></script>
```

Why Error?

**Comment by nicolafranchini** [comment]
I don't know, have you tried to load the css without the initial slash?
```<link rel="stylesheet" href="venobox/venobox.min.css" />```

**Comment by hgalytoby** [comment]
Oh!  

It turns out that the problem is here! 

Thank you very much!!
