### ISSUE TITLE
How to use full screen? 

### ISSUE THREAD

**Issue by hgalytoby** [nicolafranchini/VenoBox#160]
I used Google Drive Iframe

Hope to be able to use the full screen function

But i can't use 

![image](https://user-images.githubusercontent.com/50397689/120070390-e26b4e80-c0bc-11eb-98b6-3503126879a2.png)

When I clicked it once, a message was displayed. 

![image](https://user-images.githubusercontent.com/50397689/120070410-f8790f00-c0bc-11eb-9fb4-55cdcd4986b3.png)

Is there a way to do it?

Thank you.

**Comment by nicolafranchini** [comment]
Hi, I'm sorry, I never worked with Google Drive Iframe, but I would be curious with that link "Learn More" ;)
