### ISSUE TITLE
Could not find a declaration file for module venobox

### ISSUE THREAD

**Issue by hallowichig0** [nicolafranchini/VenoBox#172]
Hi,

I just want to declare this venobox using import like this:
`import VenoBox from 'venobox';`

But it throws warning:

Could not find a declaration file for module 'venobox'. 'website/node_modules/venobox/dist/venobox.min.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/venobox` if it exists or add a new declaration (.d.ts) file containing `declare module 'venobox';`

**Comment by nicolafranchini** [comment]
Hi, I'm not totally sure, but you could try to import `VenoBox` from /src/venobox.esm.js. 

/dist/venobox.min.js is the built and compressed version, not the module.

**Comment by reshaelfianur** [comment]
I have the same error. I have tried the method you suggested but it didn't work.

VenoBox from /src/venobox.esm.js
Or 
VenoBox from /venobox/src/venobox.esm.js
