### ISSUE TITLE
No "destroy" Method?

### ISSUE THREAD

**Issue by sayontan** [nicolafranchini/VenoBox#173]
The documentation says:

`venobox.destroy();        // Destroy the plugin`

However, there is no such method in the script. Is there a way to unbind an existing instance or reset its contents? I would like to add new images to an existing gallery dynamically.

**Comment by sayontan** [comment]
For now I have a workaround - I am reinitializing the lightbox with the same selector, and that seems to be taking care of the issue.

**Comment by nicolafranchini** [comment]
Yes, if you reinitialize the same selectors after adding new element to the collection, the script skips the already initialized elements. Sorry, the destroy() function was inside the old jquery version, I forgot to remove it from the documentation.
