### ISSUE TITLE
Re-initialize

### ISSUE THREAD

**Issue by Luckyfella73** [nicolafranchini/VenoBox#176]
Hello,

I had to add a content-blocker (Borlabs) because of GDPR reasons for Youtube embeds.
The content-blockers removes the HTML needed for Venobox (including the trigger class (.venobox)
and after consent the HTML is pushed back into the DOM. 

I guess on page-load the Venobox script looks for the trigger class and if not found nothing happens of course.
Pushing new content to the DOM is not recognized by Venobox and that's why the Venobox script doesn't fire anymore.

So my question is:

Is it possible to re-initialize the Venobox script? And if yes - how can I do that?

**Comment by nicolafranchini** [comment]
have you tried to call it again after the DOM is updated?

```
new VenoBox({
    selector: '.my-custom-links',
});
```
