### ISSUE TITLE
Open() fails when VenoBox instance is assigned to a variable.

### ISSUE THREAD

**Issue by K-Thompson** [nicolafranchini/VenoBox#179]
If I use VenoBox this way:

```
// Initialize venobox as a variable
var venobox = new VenoBox();

venobox.open('#my-link'); // Open specific item
```

`Open()` fails at the last line:

```
   /**
    * Open item.
    */
    function open(obj) {

       if (document.body.classList.contains('vbox-open') || !obj) {
           return false;
       }

       if (obj.settings.onPreOpen && typeof obj.settings.onPreOpen === 'function') {
```

The problem is, that the parameter is not an object and the first test assumes that it is.

Also, if I pass in this documented object:

`var vboxOptions = {`

the code still fails because settings is not an attribute of the object.

Am I misunderstanding something?

FYI, my use case is to display dynamically created HTML or iFrame.

**Comment by tefod-zz** [comment]
Have the same issue. Opening per JS does not work either for me.
@K-Thompson did you find a workaround?

**Comment by K-Thompson** [comment]
@tefod-zz No. I decided against using VenoBox - probably for this reason.

**Comment by tefod-zz** [comment]
I had to take also something else. May I ask what you chosen instead of VenoBox?
For me [glightbox](https://github.com/biati-digital/glightbox) did the trick. The setup and usage is pretty similar and works automatically per classes and can be opened per JS. 

```
const force2dLightBox = GLightbox({
	elements: [
		{
			href: './index.html?set=' + src,
			width: window.innerWidth / 1.1,
			height: window.innerHeight / 1.1,
		},
	],
	openEffect: 'zoom', 
	closeEffect: 'fade',
});
force2dLightBox.open();

**Comment by nicolafranchini** [comment]
Sorry for the wrong hint inside the documentation, this is the right way to call venobox.open()

```
// Open specific item
var myLink = document.querySelector('#my-link');
venobox.open(myLink);
```
