### ISSUE TITLE
Cant destroy and restart on ajax call

### ISSUE THREAD

**Issue by gcooke-hdk** [nicolafranchini/VenoBox#185]
Hi, 

I am trying to use destroy but the console just keeps giving me the 'venobox.destroy is not a function' message. 

Can you advise what might be going on or what I need to do to destroy and refire the venobox on each ajax load?

**Comment by nicolafranchini** [comment]
Yep, the destroy function doesn't exist anymore, but you could try to just reinitialize after the ajax call
