### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by JohnieWalkerCZ** [nicolafranchini/VenoBox#186]
While using your plugin I noticed a mistake in your documentation.
In the paragraph [Methods](https://veno.es/venobox/#section_methods), the method `venobox.open()` is written with a selector for an element(`venobox.open('#my-link');`) but to make it work you have to pass the element itself(`venobox.open(my-element);`).

**Comment by nicolafranchini** [comment]
You are right, thank you. I've updated the documentation
