### ISSUE TITLE
venobox cannot zoom in and zoom out using android OS

### ISSUE THREAD

**Issue by faizlongbow** [nicolafranchini/VenoBox#187]
Hi , currently got issue on to zoom in and zoom out the images using venobox. I have tried using it on apple OS and it works but for android OS it got problem to zoom in and out the images. When i tried it on android mobile phones it cannot works.

**Comment by nicolafranchini** [comment]
I don't know, I've tested on IOS and also Android (chrome), and the images inside the demo can be zoomed.
