### ISSUE TITLE
onPreOpen function not handling return values

### ISSUE THREAD

**Issue by jonathanrico** [nicolafranchini/VenoBox#190]
Hi Nicola,

Thanks so much for writing this lightbox, it's awesome! Just noticed the onPreOpen function is not handling return values but the doc says it should: ` // is called before the venobox pops up, return false to prevent opening;`

Would be great to prevent opening as I have a scenario where I want to avoid the lightbox if its part of a drag operation.

**Comment by nicolafranchini** [comment]
Hi, the onPreOpen callback can be a function which returns values, or directly `onPreOpen: false` if you want to prevent the popup opening. check this example, the first link returns the venobox object and a custom message (look inside the console), the second link does not open the popup.
https://codepen.io/nicolafranchini/pen/ZEPKxZP

**Comment by jonathanrico** [comment]
Hey Nicol, thanks for the response!

That works but if you want to perform logic in the function and then return
false from within the function in certain conditions then it doesn’t seem
to work.

Jonathan Rico.

**Comment by nicolafranchini** [comment]
Ok, I've updated the script, now the return value is inside the function. But if you want to perform other actions and not open the popup, why don't you rather exclude these items from the venobox initialization?
https://codepen.io/nicolafranchini/pen/ZEPKxZP

**Comment by jonathanrico** [comment]
Thanks Nicola! 

My use case is not that straightforward. I have draggable components that contain images. If a user happens to drag (instead of click) a component from the image area in the component I do not want it to trigger the lightbox. So the returned value from PreOpen depends on some additional state the parent element has. Hope that makes sense.
