### ISSUE TITLE
maxWidth does not work correctly due to overwriting width in styles

### ISSUE THREAD

**Issue by maks-oleksyuk** [nicolafranchini/VenoBox#193]
Check out examples of implementations with videos on the documentation site.

Pay attention to the example with a simple video (mp4), it uses the following code:

```html
<a class="my-video-links" data-autoplay="true" data-vbtype="video" data-ratio="1x1" data-maxwidth="400px" href="my-video.mp4">MP4</a>
```

Here the `data-maxwidth="400px"` attribute is specified, which should limit the width to `400px`, but it does not happen
The reason for this is the definition of the following styles in the [src/venobox.css](https://github.com/nicolafranchini/VenoBox/blob/master/src/venobox.css#L235-L237) file:
```css
.vbox-child.venoratio, .vbox-child.vbox-inline{
    max-width: 100%;
}
```
Perhaps the solution is to replace `max-width` to `width`

**Comment by nicolafranchini** [comment]
Thanks for the note, it was mainly a wrong order of the rules inside the css. Check the latst version.
