### ISSUE TITLE
Windows Defender Wacatac detected

### ISSUE THREAD

**Issue by iamalexm** [nicolafranchini/VenoBox#194]
Hi, 

I'm intrested of using your script, but Windows Defender warns me about a potential Wcatac.B!ml malware in your code.

![image](https://github.com/nicolafranchini/VenoBox/assets/46227288/d7d9a5f4-b2ac-4f12-9097-ff791e91253d)

Am I the only one having this warning?

Thanks,

Alex

**Comment by nicolafranchini** [comment]
Hi, I never used Windows, and inside the package there is nothing like that, you can browse and check any file directly here on github.
Maybe WIndows Defender is giving you a false positive, or you have something else on your pc.
You can also look here for further info:
https://answers.microsoft.com/en-us/windows/forum/all/how-can-i-know-if-wacatacbml-is-a-false-positive/33107e01-d390-4579-aa94-625a3402d26a
