### ISSUE TITLE
Using wrapInner() causes nested iFrames to reload

### ISSUE THREAD

**Issue by kanduvisla** [nicolafranchini/VenoBox#30]
When you have a page with iFrames, the `wrappInner()`-method on line [77 of venobox.js](https://github.com/nicolafranchini/VenoBox/blob/master/venobox/venobox.js#L77) causes iFrames on the page to reload (since the whole DOM would be reloaded).

A better approach would be to replace `wrapInner()` with `append()`. This way, iFrames don't get reloaded. Also, the styling on [line 14 of venobox.css](https://github.com/nicolafranchini/VenoBox/blob/master/venobox/venobox.css#L14) would be better of if it's `fixed`. That way, when scrolling the overlay stays visible.

**Comment by nicolafranchini** [comment]
try the last release: different approach, without body wrapping ;)
