### ISSUE TITLE
Pauses HTML5 video on close

### ISSUE THREAD

**Issue by generatepress** [nicolafranchini/VenoBox#33]
Love the script - thanks a lot!

One issue I'm having is I have a HTML5 video background in one of the divs on the page.

When I close the lightbox (which is inline), it pauses the HTML5 video.

Any solutions?

Thanks!

**Comment by pangolingo** [comment]
Could this be related to #30 ? On close it looks like the script is unwrapping the body, which may stop or reload the videos.

**Comment by nicolafranchini** [comment]
try the last release, now the overlay goes over the body, without wrapping it, it should solve this kind of issues
