### ISSUE TITLE
No show on reload

### ISSUE THREAD

**Issue by garyee** [nicolafranchini/VenoBox#39]
Hi,

so I got a strange fault. I have a site with some venobox links on it. Every time I reload the page (cmd + F5 in Firefox) the first venobox link I click will just show the progress wheel turning.
The resources will just get loaded up to "next.gif" and nothing happens, aside form the progress wheel.
That fault is strange because my colleague does not experience the same behavior when he accesses the same site.

**Comment by nicolafranchini** [comment]
Sorry, I don't know what could it be, just try the last release of the script (1.5.3), there are some improvements in compatibility
