### ISSUE TITLE
How to disable the $(window).scrollTop();

### ISSUE THREAD

**Issue by Le-future** [nicolafranchini/VenoBox#41]
Hey man,

Your Venobox rocks definitely, it fits perfectly with my design, I got just a problem and I can't figure it out.

When I click on a picture to open the venobox, there is an immediate scroll top and when I close it, the scroll down is done.

I try to disable this scroll top to stay at the same place on my page but impossible...

My div is with an overflow scroll for your information,

Hope to read you soon,

Thanks!

**Comment by Le-future** [comment]
Solution : Comment line 77 of venobox.js : 

$('body').wrapInner('<div class="vwrap"></div>');

**Comment by Le-future** [comment]
Solution : Comment line 77 of venobox.js : 
```
$('body').wrapInner('<div class="vwrap"></div>');
```

**Comment by nicolafranchini** [comment]
Hi Le-future, please take a look at the latest release, I used a different approach, now the script does not wrap the body and doesn't need to set the scroolTop value

**Comment by Le-future** [comment]
Hey!

Okay thanks, for the moment I succeeded to have a positive result with a few modifications on the previous version :-)

I will use the new one for the next, I'll mention strongly your plugin in the description of my work!

Best,
