### ISSUE TITLE
Cookie feature !!

### ISSUE THREAD

**Issue by fourroses666** [nicolafranchini/VenoBox#42]
I like the script. Maybe you like this feature.

I have succesfully used a cookiescript on an other custom popup.
The popup opens automaticly on previewing the page.
Then set a timeout of x minutes and the popup doesn't show anymore.

All I did is used these scripts:

(cookie-wrap-popup needs to be an other class*) :
https://gist.github.com/fourroses666/243d04e351b26465e886

Grabbed form https://github.com/carhartl/jquery-cookie :
https://gist.github.com/fourroses666/502fc4a40b5f5a6d4e2c

I'm not a coder so leave it up to you.

**Comment by nicolafranchini** [comment]
Hi, thanks for the suggestion, but I prefer to keep the script simple, and possibly expandable
