### ISSUE TITLE
iPad 2 - Safari crashes when I interact with the lightbox

### ISSUE THREAD

**Issue by robbiegod** [nicolafranchini/VenoBox#50]
I am using Venobox on our website which is still under development.  I am testing it on an iPad.  When i click a link that opens the lightbox, the lightbox opens.  I am opening a page that has a slider inside of it that displays some photos.  When i swipe in the lightbox, Safari completely crashes.  The screen goes blank and then safari quits.  

I have tested the slider on different pages where i don't open it in a lightbox and the slider works fine.

**Comment by nicolafranchini** [comment]
maybe there's some conflict
