### ISSUE TITLE
Wrong margin when images in AJAX content

### ISSUE THREAD

**Issue by mciszczon** [nicolafranchini/VenoBox#51]
There is a problem when loading a content into Venobox using AJAX. If there is an image in the content to be loaded, it will often cause the plugin to add wrong margins (top + bottom) to the container (`.vbox-content`).

I thought for a while and the reason is simple: if the content is short enough to fit in the viewport, the plugin calculates margins that must be added to the `.vbox-content` element, so it's centered vertically. The problem is, that all this math takes places **before** the image is loaded, so it appears after Venobox is opened. But the margins stay the same, resulting in a huge spacing from the top and bottom.

Workaround could be making sure that images you put in there are always the same size, so you could give the `img` element width and (most importantly) height. Then they would take up the required size even before loaded.

The better way to fix this would be to make the layout use `display: table` (on parent) and then children (with the content) to use

```
display: table-cell;
vertical-align: middle;
```

This would need a lot of work I guess.

**Comment by nicolafranchini** [comment]
in the last version the window height gets recalculated after every image inside the window has been loaded

**Comment by mciszczon** [comment]
Great to see VenoBox is still alive! Keep up the good work and thanks.
