### ISSUE TITLE
Show caption?

### ISSUE THREAD

**Issue by waldbach** [nicolafranchini/VenoBox#54]
Hi,
Great script. Just wondering how to show a caption that goes with the image?
I am using the script in a Wordpress setup with Advanced Custom Fields. It works great, but I don't know how I should be able to display a caption.

This is my PHP function:
```$thumbs = get_sub_field('thumbnail_gallery');
         if( $thumbs ): ?>
                <div class="veno-container">
                    <div class="veno-thumbs">
                    <?php foreach( $thumbs as $image ): 
                          $caption = $image['caption']; ?>     
                            <a class="venobox" data-gall="myGallery" href="<?php echo $image['sizes']['large']; ?>"><img src="<?php echo $image['sizes']['medium']; ?>" alt="<?php echo $caption; ?>" /></a>
                    <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ```

and my js:
`				$('.venobox').venobox({
					titleattr: 'alt'
				});
 `

**Comment by garyee** [comment]
firstly... when you post code please do format it before you do!
secondly read the [documentation](http://lab.veno.it/venobox/) and do look at the code samples!

if you a caption for your images (it will be displayed over the image), you have to add an title to the a-tag

this schould work (untested):
```
<?php $thumbs = get_sub_field('thumbnail_gallery'); if( $thumbs ): ?>
  <div class="veno-container">
    <div class="veno-thumbs">
     <?php foreach( $thumbs as $image ): $caption = $image['caption']; ?>
            <a class="venobox" data-gall="myGallery" href="<?php echo $image['sizes']['large']; ?>"
              title="<?php echo $caption; ?>">
                <img src="<?php echo $image['sizes']['medium']; ?>" alt="<?php echo $caption; ?>" />
            </a>
      <?php endforeach; ?>
   </div>
 </div>
 <?php endif;>
```

**Comment by waldbach** [comment]
Sorry and welcome to my first Github code post! ;)
I did read the documentation, but could not completely understand how to solve this.
Thanks for your solution, @garyee !

**Comment by garyee** [comment]
You shall be excused ;) no problem

**Comment by waldbach** [comment]
Strange enough, I can't get the code right, not even with three backticks. Hmmm... I need some more practice.
