### ISSUE TITLE
inline div, input fields, get no values - when it shows inside a VenoBox

### ISSUE THREAD

**Issue by MarBel78** [nicolafranchini/VenoBox#55]
HI, venobox is great - but for my reason i need to save values from input fields, inside a inline div showing inside a venobox.
Get no value ( input id="newlastname" type="text" ) with jQuery $('#newlastname').val(), when i change the Value in the Form. When there is a fixed value (input id="newlastname" type="text" value="smith") i get always this value, also when i change it at the form.

Any ideas ?

Thanks a lot !
Best Regards, Marcel

**Comment by nicolafranchini** [comment]
Hi Marcel, the "inline" mode redraws the hidden div inside of the overlay window, so maybe that the script finds 2 inputs with the same id #newlastname and get confused.. try to change id="newlastname" with class="newlastname", and update the value with $('.newlastname').val()

**Comment by MarBel78** [comment]
Thanks, now it works, when i select the second one: $('.newlastname:last').val() !
