### ISSUE TITLE
loads at the top of the page

### ISSUE THREAD

**Issue by gemelli2** [nicolafranchini/VenoBox#56]
Hi i have a page with many youtube testimonials : http://www.premierortho.com/testimonials.php
all the sudden i have noticed that when i click to view - it opens an iframe at the top of the page and so if you are at the bottom of the page and clicking to view, you don't see the iframe.

any ideas of how to fix??

**Comment by nicolafranchini** [comment]
Hi, try to download and replace the script with the latest version, I see that you still have .vbox-overlay with position:absolute instead of position:fixed, the last version should fix your problem

**Comment by gemelli2** [comment]
That was it - thanks so much!!!
ᐧ

2twinsdesign

website design *|* graphic design *|* SEO

Phone & Text: (484) 321-3289
info@2twinsdesign.com | www.2twinsdesign.com

**Comment by 3dluvr** [comment]
Hi,

This issues seems to still persist on mobiles, whereas a link inside a div with overflow will cause a scroll back to the top of that div, upon closing the overlay view.
