### ISSUE TITLE
add swipe support

### ISSUE THREAD

**Issue by oozrafa** [nicolafranchini/VenoBox#59]
Is it possible to add support for swipe (left and right). This is the natural behaviour on mobile devices.
If not then how do I trigger next/previous slide via API?

**Comment by ericthayer** [comment]
I don't think it's possible since the prev & next images are not in the DOM, they are injected on call. Better for performance IMO.

![screen shot 2015-12-22 at 4 14 33 pm](https://cloud.githubusercontent.com/assets/2737007/11968228/2cadb49c-a8c7-11e5-9a6b-eccd4f6dcb3c.png)

**Comment by groundnation** [comment]
+1, swipe support really would make this the perfect lightbox

**Comment by oozrafa** [comment]
It doesn't have to animate the next slide in, but just do same as when
pressing the next or previous buttons.

**Comment by nicolafranchini** [comment]
I'm looking for a light and widely supported way to detect the left-right swipe, and possibly add a fake slide effect to the items (e.g: slide out - load - slide in)
