### ISSUE TITLE
AJAX Call : cannot increase the height, width 

### ISSUE THREAD

**Issue by PrajaktaSoftware** [nicolafranchini/VenoBox#62]
Dear sir

i am making ajax call

 <a href="shopdetailfill.php?shopid=<?php echo $rows['shopid'];?>" data-type="ajax" class="venobox">

a pop up div is displayed
the size of this div is small

i want to increase the size of the div
pls help 

What I tried

<link rel="stylesheet" href="venobox/venobox.css" type="text/css" media="screen" />

<script type="text/javascript" src="venobox/venobox.min.js"></script>

<script >
 $(document).ready(function(){

    /* default settings */
    $('.venobox').venobox(); 

    /* custom settings */
    $('.venobox_custom').venobox({
        framewidth: '1100px',        // default: ''  // tried to increase width
        frameheight: '900px',       // default: ''    // tried to increase Height
        border: '10px',             // default: '0'
        bgcolor: '#333',         // default: '#fff'
        titleattr: 'data-title',    // default: 'title'
        numeratio: true,            // default: false
        infinigall: true            // default: false
    });

    /* auto-open #firstlink on page load */
    $("#firstlink").venobox().trigger('click');
});
</script>

**Comment by nicolafranchini** [comment]
that should be fixed in the last version
