### ISSUE TITLE
Click twice to initiate VenoBox

### ISSUE THREAD

**Issue by joshuaiz** [nicolafranchini/VenoBox#63]
I have a Play/Pause button to click to initiate VenoBox. After the initial page load you have to click the button twice to initiate VenoBox. On subsequent tries, you only have to click the button once.

Here's what I have:

    jQuery(document).ready(function($){
         $('.venobox_custom').click(function(ev) {
      
         ev.preventDefault();

        /* custom settings */
        $('.venobox_custom').venobox({
             framewidth: '560px',
             frameheight: '315px',
        });
    });

And the html is just:

    <a class="venobox_custom playpause" data-type="youtube" href="https://youtu.be/9P6VU9DqVZo?rel=0&autoplay=1"></a>

Any ideas on how to trigger on 1 click?

Thanks!

**Comment by nicolafranchini** [comment]
Hi joshualz, venobox already triggers the click, try to set simply
```
jQuery(document).ready(function($){
    /* custom settings */
    $('.venobox_custom').venobox({
         framewidth: '560px',
         frameheight: '315px',
    });
});
```

**Comment by joshuaiz** [comment]
Brilliant - thank you.
