### ISSUE TITLE
Images wont load

### ISSUE THREAD

**Issue by thomasncurry** [nicolafranchini/VenoBox#64]
Hi 

i have downloaded VenoBox all was working well i setup a test image worked fine but as soon as i added another it all went wrong none of my images would open just the constant pre-loader and the YouTube videos just display a content not found and this ive tried with a few different videos with both long URL and short URL 

is it just ,e or has anyone else had this issue?

**Comment by garyee** [comment]
just you! what question is that ? if you post your code it is easier to get help ;)
