### ISSUE TITLE
[Feature request] Ability to embed YouTube video list

### ISSUE THREAD

**Issue by ahmadalfy** [nicolafranchini/VenoBox#66]
YouTube video list would be an awesome addition to the plugin. Will try to fork VenoBox and do it.

**Comment by nicolafranchini** [comment]
what are youtube video lists? do you have an example of embeddable url? because playlists seem to have the same sharing links of single videos

**Comment by ahmadalfy** [comment]
There is a query string called "list" that display the list in the video

http://codepen.io/anon/pen/xqpWqM

I don't think it worked before. Not sure if it works now

**Comment by nicolafranchini** [comment]
Oh, sorry, I was un-logged and YT wasn't showing me the list sharing option but only the single video.
In the last version venobox gets only the id from the various types of urls, but it shouldn't be difficult to search and extract the query string `?list=`, I will include it in the next version (this time hopefully some days, not years) ;)

**Comment by ahmadalfy** [comment]
I will be happy to do it
