### ISSUE TITLE
Open another venobox from opened venobox

### ISSUE THREAD

**Issue by martinb2** [nicolafranchini/VenoBox#67]
Hi,
Is it possible to make initialization after opening venobox with data-type="ajax", where gallery is loaded and I want make a separate previews of images in another instance of Venobox ?
But when I close image preview, venobox with ajax still displaying content of gallery.

**Comment by alvarosaco** [comment]
Hi @martinb2 
Any advance in this issue? I'm trying something similar without success.

**Comment by nicolafranchini** [comment]
a quick solution would be calling the gallery with data-vbtype="iframe", and outputting the gallery in a separate page which also loads and calls venobox on its images
