### ISSUE TITLE
Allow other youtube links

### ISSUE THREAD

**Issue by q2apro** [nicolafranchini/VenoBox#69]
The URL is not always provided as `http://www.youtu.be/your_video_id` so the recent `function loadYoutube` will fail. 

I updated the code so that also links like `https://www.youtube.com/watch?v=cgmjGIQ-G3c` will be accepted.

https://github.com/nicolafranchini/VenoBox/pull/68

**Comment by nicolafranchini** [comment]
I used a slightly different function to improve that part, included in VenoBox 1.7
