### ISSUE TITLE
Adding &rel=0 to function loadYoutube()

### ISSUE THREAD

**Issue by ryanbigfresh** [nicolafranchini/VenoBox#73]
I am trying to concatenate &rel=0 to the URL here:
```javascript
content.html('<iframe class="venoframe" allowfullscreen src="http://www.youtube.com/embed/'+videoid+'"></iframe>')
      updateoverlay();
```
when I do so, I am unsuccessful. Your assistance would be greatly appreciated.

Thanks.

**Comment by nicolafranchini** [comment]
Hi, did you try to add &rel=0 after videoid ?
```
content.html('<iframe class="venoframe" allowfullscreen src="http://www.youtube.com/embed/'+videoid+'&rel=0"></iframe>')
```

**Comment by ryanbigfresh** [comment]
@nicolafranchini I did, and that was unsuccessful. I am really stumped here. Thanks for the quick response.

**Comment by nicolafranchini** [comment]
uhm, try ```?rel=0``` instead of ```&rel=0```, as maybe it's the first and only parameter

**Comment by ryanbigfresh** [comment]
@nicolafranchini  I tried that too. If you visit http://stage.cascadedafo.com/library/DAFO and click on the first video - inspect the iframe element in the vbox and you will see that ?rel=0 has not been added to the youtube url. Strange, huh?

**Comment by nicolafranchini** [comment]
I just did a test on the online demo, and by my side it works: http://lab.veno.it/venobox/
inspect the source and you will see the ?rel=0 inside the youtube iframe src.. so I don't know.. just be sure to include the modified version of venobox.js
