### ISSUE TITLE
?rel=0 not working still

### ISSUE THREAD

**Issue by ryanbigfresh** [nicolafranchini/VenoBox#74]
Hi Nicola, 

I hate to bother you again. I added this to the code in the live server and it still is not working. See attached image. The link to this page is: http://cascadedafo.com/library/DAFO
 Thank you so much for your help!

![screen_shot_2016-01-14_at_10_53_24_am](https://cloud.githubusercontent.com/assets/16694261/12334159/58407a16-baad-11e5-9d6d-258a86bf711c.png)

**Comment by nicolafranchini** [comment]
yep, that's because the script only gets the video ID from the url, not additional paramenters.
I've added ?rel=0 to all youtube videos, it will be included in version 1.7, out soon.
