### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by marvinhagemeister** [nicolafranchini/VenoBox#77]
Since npm3 more and more people seem to be switching away from bower (at work we already did jus that). I'd be awesome if venobox gets published as an npm package, since it's one of the most loed lightbox plugin in our team.

**Comment by ibarral** [comment]
+1

**Comment by KasperAndersson** [comment]
+1

**Comment by nicolafranchini** [comment]
Well, after one year, I will try, I'm going to publish the new  version :D
