### ISSUE TITLE
Youbte https Problem

### ISSUE THREAD

**Issue by garyee** [nicolafranchini/VenoBox#80]
Hi,

there is a small Problem with embeding Youtube Videos.
If the Video URL is not right the youtube-player will behave strange.. like this (notice the missing buttons)

![unbenannt](https://cloud.githubusercontent.com/assets/5537949/13076712/86fa6b52-d4b4-11e5-8b53-f2b88e89302f.png)

the solution is to put the

https://
in line [383](https://github.com/nicolafranchini/VenoBox/blob/master/venobox/venobox.js#L383)

**Comment by nicolafranchini** [comment]
ok, thanks https:// added
