### ISSUE TITLE
Attaching events to the tigger element

### ISSUE THREAD

**Issue by ahmadalfy** [nicolafranchini/VenoBox#82]
Venobox seem to stop propagation of the click events on the trigger. When I try to listen to a click to the link using jQuery the event never fires. Is there a way to disable that?

**Comment by ahmadalfy** [comment]
I found it
https://github.com/nicolafranchini/VenoBox/blob/master/venobox/venobox.js#L57
Is there a reason why you are doing this?

**Comment by nicolafranchini** [comment]
I removed the stopPropagation(), honestly I don't remember why it was there, it seems to work well anyway. I'm going to publish the new version.
