### ISSUE TITLE
Close Venobox inside an iFrame

### ISSUE THREAD

**Issue by saliraza110** [nicolafranchini/VenoBox#84]
Hi Everyone,

I wanted to close a 'venobox' inside an iframe.
Example. I open a external page on venobox iframe. I have a button on that external page, on-click of that button I wanted to close the venobox.

I would appreciate if someone answer me this query.

Thanks

**Comment by garyee** [comment]
First things first... what you are trying to do sounds pretty dirty, as Iframe things are.
Secondly, is the content in the IFrame coming from the same domain as the sourounding page?
If yes ... why would you use an iframe for that? But if you absolutley must do that there may be a [solution](http://stackoverflow.com/a/1451455/2529666)
You could trigger a click on the close button, or call the close-function of the venobox from inside of the iframe, or get a clicklistener hooked on button from the outside
If no ... no chance! It is a security thing. Imaging someone would load your website in an iframe and could anything he/she want's with it ... an therefor the users.
