### ISSUE TITLE
Add swipe support with TouchSwipe-Jquery-Plugin

### ISSUE THREAD

**Issue by eduardobelchior** [nicolafranchini/VenoBox#85]
Is it possible to add support for swipe (left and right). This is the natural behaviour on mobile devices.
If not then how do I trigger next/previous slide via API TouchSwipe-Jquery-Plugin?

code html:
`<div id="hover-bg">
                                <a class="venobox" data-gall="placas" href="fotos/fotos/10f218859743e9bc947c81570c1066f1.jpg" title="TEXTO DA IMAGEM">
                                    <div class="hover-text">
                                        <p class="lead">Placas<br />e Fachadas</p>
                                        <div class="hline"></div>
                                    </div>
                                    <img src="img/portfolio/01.jpg" class="img-responsive" alt="...">
                                </a>
                                <a class="venobox" data-gall="placas" href="fotos/fotos/af62036784528f8773a96bd71b5557b3.jpg" title="TEXTO DA IMAGEM"></a>
                                <a class="venobox" data-gall="placas" href="fotos/fotos/cfd8447feaa62c6dcc6cbc1ec4426934.jpg" title="TEXTO DA IMAGEM"></a>
                                <a class="venobox" data-gall="placas" href="fotos/fotos/d6a7f824cf38c0a9d04493f394454300.jpg" title="TEXTO DA IMAGEM"></a>
                                <a class="venobox" data-gall="placas" href="fotos/fotos/4d801e94fd84df663485178959bf6783.jpg" title="TEXTO DA IMAGEM"></a>
                            </div>`

script:
`<script id='code_1'>
            $("#hover-bg a").swipe( {
                //Generic swipe handler for all directions
                swipe:function(event, direction, distance, duration, fingerCount, fingerData) {
                    if(direction == "left"){
                        // Method Next
                        alert("Next");
                    } else if (direction == "right"){
                        // Method previus
                        alert("Previus");
                    }
                }
            });
        </script>`

API: https://github.com/mattbryson/TouchSwipe-Jquery-Plugin

**Comment by nicolafranchini** [comment]
sorry, there is no method to call externally next prev gallery. but I'm trying to integrate the swipe detection

**Comment by underlircs** [comment]
Do you know when externally calling next/previous will be released?
