### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by mciszczon** [nicolafranchini/VenoBox#87]
Hi.

I'm using Venobox with jQuery 3.1.0 on website I'm working on. I've been using venobox sucessfully to load YouTube videos and to load AJAX content. Everything working fine.

Then I wanted to use venobox to load an image. The most default of default uses :P And what happens is that when I click the image, overlay opens as it should. But I get this message into the console log:

![venobox](https://cloud.githubusercontent.com/assets/1078369/18473301/6fcd7ef8-79bc-11e6-9e21-fd1e66525214.png)

And then I am not able to close the overlay with the photo. Clicking the "X" button definietly is doing something, as there again appears website scrolling bar and I can easily scroll through page. Also, the `.vbox-open` class is removed from the body. But overlay styles are not changed (`opacity` is still `1` and so on).

Thanks.

**Comment by chrisbeaver** [comment]
I rigged this to work. I don't know why the problem occurs, but I know I'm loading jQuery 3.11, while the working examples on the product page use jQuery 1.11.  It appears to be somethign with the index in an .each() iteration.  Anyway, the code was breaking on a preloadFirst() method call. I commented the code out, and it worked. 

This is line 399 of venobox.js, just get rid of that if confitional.

> // if(this.complete) $(this).load();

```
/* -------- PRELOAD IMAGE -------- */
    function preloadFirst(){
        prima = $('.vbox-content').find('img');
        prima.one('load', function() {
          updateoverlay();
        }).each(function() {
          // if(this.complete) $(this).load();
        });
    }
```

**Comment by nicolafranchini** [comment]
Yes, the new VenoBox 1.7 has been tested also with jQuery 3 and the deprecated functions are removed
