### ISSUE TITLE
Open specific lightbox (in gallery) based on hash. 

### ISSUE THREAD

**Issue by mvaneijgen** [nicolafranchini/VenoBox#88]
I have a site with a gallery lightbox with all kinds of vimeo video's. Is it possible to open a specific video with the url `mysite.com/#video7`.

 I was thinking about adding a custom `data-attr` for each video like this:

`<a href="https://vimeo.com/123456789" data-myhash="video1">Video 1>`
`<a href="https://vimeo.com/123456789" data-myhash="video2">Video 2>`
`<a href="https://vimeo.com/123456789" data-myhash="video3">Video 3>`
...
`<a href="https://vimeo.com/123456789" data-myhash="video27">Video 27>`

But I have no idea how to implement this or maybe it already is a feature that I am missing?

**Comment by garyee** [comment]
Normally you can do this with a simple jquery function that reads the hash (or URL parameter) then finds the venobox a-tag to the hash and does:

> $('#venobox-345345').trigger('click');

**Comment by mvaneijgen** [comment]
@garyee thanks, didn't seem to difficult now you explained it, so if anyone comes across this here is a snippet I used. 

```
jQuery( document ).ready(function() {
  var currentLocationHash = window.location.hash;
  var openVenoHash = currentLocationHash.replace('#','');
  jQuery(".alloy-project[data-myhash='" + openVenoHash + "']").trigger( "click" );
});
```
