### ISSUE TITLE
Closing overlay/inline content using another element

### ISSUE THREAD

**Issue by brandercreative** [nicolafranchini/VenoBox#89]
Hi All,

I've tried adding a div with class .vbox-close into the inline content, upon clicking there is no response.

Any tips on creating another div to close venobox.

**Comment by nicolafranchini** [comment]
Hi, the next version will have the method `closeVB()`, so you will be able to do

```javascript
var venobox = $('.venobox').venobox();

$(document).on('click', '.custom-close', function(){
    venobox.closeVB();
});
