### ISSUE TITLE
Load popup only once?

### ISSUE THREAD

**Issue by asifkabani** [nicolafranchini/VenoBox#90]
Trying to figure out if there is anyway to modify this code:

`/* auto-open #firstlink on page load */
    $("#firstlink").venobox().trigger('click');`

So that the first time someone visits the page it auto pops up, but then after that it does not.

**Comment by garyee** [comment]
For Autoload look at #88. For not loading it again... there should be a destructor, but there isn't feel free to PR one. You would need to unbind the click-Listener amongst other things.

**Comment by asifkabani** [comment]
Thank you, another question. I have another code which is conflicting with the data-type="iframe" which I have set on the inline element. Is there a way to call the data-type at the bottom where I initialize the jquery code for venobox? Because I have to have another jquery plugin call it's data types on the same inline element.

**Comment by garyee** [comment]
I did not get the question, what do you mean by calling the data-type? I don't know if it is a good idea to have two plugins working with the same dom element.

**Comment by nicolafranchini** [comment]
in version 1.7 the ```data-type``` has been renamed in ```data-vbtype"
