### ISSUE TITLE
Opening up last image first in gallery

### ISSUE THREAD

**Issue by JoshuaElliff** [nicolafranchini/VenoBox#91]
Hi, I will just say that I'm not a developer I'm a designer so I'm sorry if this is super basic. 

I'm using a downloaded theme which incorporates Venobox and it looks great, however one small problem I'm having is I've set up a gallery and cannot get it to open the first image first. 

eg, it opens up the lightbox and says 9/9 in the corner. 

**This is the code (again sorry if this is totally wrong) —**

 
              <div class="works-item signature-karl ImageWrapper ContentWrapperB chrome-fix works-item-one-half zoom branding">

                      <img data-no-retina alt="" title="" class="img-responsive" src="images/northengland/northengland_01.jpg"/>

                      <a  class="venobox" data-gall="portfolio-gallery" href="images/northengland/northengland_01.jpg"></a>

                      <a  class="venobox" data-gall="portfolio-gallery" href="images/northengland/northengland_02.png"></a>

                      <a  class="venobox" data-gall="portfolio-gallery" href="images/northengland/northengland_03.png"></a>

                      <a  class="venobox" data-gall="portfolio-gallery" href="images/northengland/northengland_04.png"></a>

                      <a  class="venobox" data-gall="portfolio-gallery" href="images/northengland/northengland_05.png"></a>

                      <a  class="venobox" data-gall="portfolio-gallery" href="images/northengland/northengland_06.png"></a>

                      <a  class="venobox" data-gall="portfolio-gallery" href="images/northengland/northengland_07.png"></a>

                      <a  class="venobox" data-gall="portfolio-gallery" href="images/northengland/northengland_08.png"></a>

                      <a  class="venobox" data-gall="portfolio-gallery" href="images/northengland/northengland_09.png"></a>

                          <div class="works-item-inner ContentB">
                            <p><span class="dark font3bold">North Coast of England</span></p>
                            <h3><span class="dark font3">A short photo series documenting the North coast of England in autumn 2015.</span></h3>
                          </div>
                      </a>
              </div>
              

**Here is a screenshot of how it opens —**

![screen shot 2017-02-07 at 10 08 26](https://cloud.githubusercontent.com/assets/25618598/22704687/6c5dcb0e-ed1d-11e6-942c-b72ad4190154.png)

Any help much appreciated, 

Many thanks, Josh

**Comment by nicolafranchini** [comment]
I'm sorry, you should contact the theme's authors, I don't know how the first link gets called in this gallery, I only can see a strange closing `</a>` at the end of your code
