### ISSUE TITLE
Vimeo and YouTube videos

### ISSUE THREAD

**Issue by gligorijan** [nicolafranchini/VenoBox#94]
Hi,

in my local project Vimeo or YouTube videos not working, loading animation staying forever. I've checked your demo page and problem is same.

**Comment by garyee** [comment]
If I look at the demo, all is working fine.

**Comment by gligorijan** [comment]
I'm not sure what happened yesterday, i've checked demo page from more browsers. **But now is everything ok.**

**Comment by nicolafranchini** [comment]
I'm working on the script in these days, maybe I had left a wrong option inside the demo. 
By the way, for now you need the `data-vbtype="youtube"` and `data-vbtype="vimeo"`; sinche the next version will be also valid a generic `data-vbtype="video"` for both of them.
