### ISSUE TITLE
top-margin problem when big images loads

### ISSUE THREAD

**Issue by eldan84** [nicolafranchini/VenoBox#95]
Hi Nicola,
inserted everything according to your howto, but unfortunately there is a top-margin in the lightbox.
Screenshot: http://img5.fotos-hochladen.net/uploads/bildschirmfotocfomz478h9.png
Do you have any idea?
Thanks

**Comment by nicolafranchini** [comment]
Hi Eldan, the margin-top is equal to the margin-bottom, and it's dynamically calculated to vertically center the content when it's lower than the window

**Comment by eldan84** [comment]
Thanks for your quick answer. Is it possible to stick it to the black title header?

**Comment by eldan84** [comment]
I edited it by myself. 
Changed line 686 to 
`content.css('margin-top', 0);`
and line 688 to:
`content.css('margin-top', margine);`

Keep up the great work, nice lightbox! Thanks :)

**Comment by nicolafranchini** [comment]
Thank you. Yes, that was the part to be changed.  ;)
