### ISSUE TITLE
Is there a method for open via javascript?

### ISSUE THREAD

**Issue by martinjinda** [nicolafranchini/VenoBox#97]
I'm looking for method which allows to me open some modal via javascript. I found just method for call close, next or previous.

It is somehow possible or not? 

for example: If someone come to my website with some utm parametr. I would directly open the gallery.

**Comment by nicolafranchini** [comment]
Hi, you can assign a unique ID to the link you want to open
`<a class="venobox" id="firstlink" href="..."`

initialize the plugin on doc ready

```
$(document).ready(function(){
    $('.venobox').venobox(); 
});
```

then trigger the click, if parameter is found
`$("#firstlink").venobox().trigger('click');`

**Comment by alololox** [comment]
What about for a popup that occurs on page load, which has no target element? Can you programmatically open via JS?

**Comment by saltymouse** [comment]
Any updates? I too am looking for a way to activate VenoBox purely with JS without having to reference an HTML element or link on the page.

**Comment by BigglesZX** [comment]
@alololox @saltymouse 
I solved this same issue by creating a (virtual) anchor element in JS, calling `.venobox()` on it, then triggering a click.

Something like this:

```javascript
$("<a href='...'></a>").venobox().trigger('click');
```

You can use the `gallItems` option to support a gallery of multiple items (just create multiple anchors). And you don't have to insert the element(s) into the DOM either; you can just trigger them as above.

Not the most elegant solution but it does the job.
